#!/bin/sh

#####################################################
#   ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗   #
#   ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║   #
#   ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║   #
#   ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║   #
#   ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║   #
#   ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝   #                                    
##################### By: Rxyhn  ####################

# ##############################################################################
# #                                  ENV VARS                                  # 
# ##############################################################################

## Environments
export PATH="${PATH}:${HOME}/.config/bspwm/bin"

# Parse colors from "~/.Xresources"
#xrdb -override "${HOME}/.Xfiles/catpuccin"

xrdb_query()
{
    [ -n "$XRDB_QUERY" ] || XRDB_QUERY="$(xrdb -query)"

    echo "$XRDB_QUERY" | while IFS=';' read -r STRING; do
        [ "${1}" = "${STRING%%\	*}" ] || continue
        echo "${STRING##*\	}"
        break
    done
}

getcolors()
{
    FOREGROUND="$(xrdb_query '*foreground:')"
    BACKGROUND="$(xrdb_query '*background:')"
    BLACK="$(xrdb_query '*color0:')"
    RED="$(xrdb_query '*color1:')"
    GREEN="$(xrdb_query '*color2:')"
    YELLOW="$(xrdb_query '*color3:')"
    BLUE="$(xrdb_query '*color4:')"
    MAGENTA="$(xrdb_query '*color5:')"
    CYAN="$(xrdb_query '*color6:')"
    WHITE="$(xrdb_query '*color7:')"
}

#getcolors
. xres
# ##############################################################################
# #                                  FUNCTIONS                                 # 
# ##############################################################################

# Credits to 6gk/polka
rule() { bspc rule -a "$@"  &}
config() { bspc config "$@"  &}

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################
autostart(){
# Run keybindings daemon.
pgrep -x sxhkd > /dev/null || sxhkd -s ~/.config/sxhkd/fifo &

# Run notification daemon.
dunst --config $HOME/.config/dunst/dunstrc &

# Run Picom.
picom --config $HOME/.config/picom/picom.conf &

# Run power manager.
#xfce4-power-manager &

# Wi-Fi applet
nm-applet &

# Bluetooth applet
blueman-applet &

# Wallpaper
$HOME/.fehbg
#pgrep -x xwinwrap || xwinwrap  -b -nf -ni -fs -ov -nf -- mpv --loop-file=inf --speed=1 -wid WID ~/cityange.gif &> /dev/null

# Launch bar
pkill polybar
polybar -c "$HOME/.config/polybar/config.ini" &

# Bluelight filter
# pgrep redshift || redshift -l 37:30 &

# Safeeyes
#pgrep safeeyes || safeeyes &

# Fix cursor.
xsetroot -cursor_name left_ptr&
}
autostart
# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

bspc monitor -d 1 2 3 4 5 6  

bspc rule -a kitty                       follow=on focus=on
bspc rule -a Code                        follow=on focus=on
bspc rule -a firefox                     follow=on focus=on
bspc rule -a mpv                         state=floating
bspc rule -a feh                         state=floating
bspc rule -a music						 rectangle=800x450+0+0 state=floating layer=above center=true

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

bspc config border_width 2
printf "%s\n" {left,right,bottom,top}_padding | xargs -I{} bspc config {} 8
printf "%s\n" {left,right,bottom}_monocle_padding | xargs -I{} bspc config {} -8
bspc config window_gap 7
bspc config split_ratio 0.50

bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer false

bspc config normal_border_color "$X0"
bspc config focused_border_color "$X8"
bspc config presel_feedback_color "$BACKGROUND"
#pkill borders; borders &
